version: '3'
services:
  # 上传服务（Node.js）
  uploader:
    build: .
    container_name: fenge_uploader
    restart: always
    environment:
      - PORT=3000
      - ACCESS_TOKEN=${ACCESS_TOKEN:?set ACCESS_TOKEN}
    volumes:
      - ./data:/app/data # 映射整个 data 目录到容器应用目录
    networks:
      - fenge_net

  # Nginx 门面
  nginx:
    image: nginx:alpine
    container_name: fenge_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
      - ./data/student_works:/usr/share/nginx/html/works # Nginx 直接读取作品文件
    depends_on:
      - uploader
    networks:
      - fenge_net

networks:
  fenge_net:
    driver: bridge
